Update cicd.yaml

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -62,9 +62,6 @@ jobs:
   Continuous-Deployment:
     needs: build-and-push-ecr-image
     runs-on: self-hosted
-    self-hosted:
-      runner: 'runner1'
-      ip: '192.168.1.100'
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
@@ -83,20 +80,22 @@ jobs:
       - name: Pull latest images
         run: |
           docker pull ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest
-    
-      # Uncomment the following step if you want to stop and remove the container if it's running.
-      # - name: Stop and remove container if running
-      #   run: |
-      #     docker ps -q --filter "name=cnncls" | grep -q . && docker stop cnncls && docker rm -fv cnncls
-    
+
+      - name: Stop and remove container if running
+        run: |
+          docker ps -q --filter "name=cnncls" | grep -q . && docker stop cnncls && docker rm -fv cnncls || echo "No running container to stop."
+
       - name: Run Docker Image to serve users
         run: |
           docker run -d -p 8080:8080 --name=cnncls \
             -e 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}' \
             -e 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
             -e 'AWS_REGION=${{ secrets.AWS_REGION }}' \
-            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest
-      
+            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest || { echo "Failed to run Docker container"; exit 1; }
+
       - name: Clean previous images and containers
         run: |
           docker system prune -f
+
+      - name: List Docker Images for Debugging
+        run: docker images
